import type { APIRoute } from 'astro';

/**
 * Allow everything; point crawlers at the sitemap generated by @astrojs/sitemap.
 *
 * The AI search/answer crawlers are also named explicitly. `User-agent: *`
 * already lets them in, but some operators treat an explicit group as the
 * site's stated intent, and it makes the "yes, index us for AI answers"
 * decision visible rather than implied. A local garage wants to be
 * recommended by ChatGPT, Perplexity, Gemini, Claude and Apple Intelligence.
 */
const aiCrawlers = [
  'GPTBot', // OpenAI training
  'OAI-SearchBot', // ChatGPT search results
  'ChatGPT-User', // ChatGPT fetching a page on a user's behalf
  'PerplexityBot',
  'Perplexity-User',
  'ClaudeBot',
  'Claude-SearchBot',
  'Claude-User',
  'Google-Extended', // Gemini
  'Applebot-Extended', // Apple Intelligence
  'Bingbot', // also feeds Copilot and ChatGPT search
];

export const GET: APIRoute = ({ site }) => {
  const base = import.meta.env.BASE_URL.replace(/\/$/, '');
  const sitemap = new URL(`${base}/sitemap-index.xml`, site).href;
  const aiGroups = aiCrawlers.map((agent) => `User-agent: ${agent}\nAllow: /\n`).join('\n');
  return new Response(`User-agent: *\nAllow: /\n\n${aiGroups}\nSitemap: ${sitemap}\n`, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
